kind: PersistentVolume
apiVersion: v1
metadata:
  name: cuong-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: cuong-claim
  hostPath:
    path: "/tmp/data01"
